name: Deploy to Cloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PREFECT_API_KEY : ${{ secrets.PREFECT_API_KEY }}
  PREFECT_API_URL : ${{ secrets.PREFECT_API_URL }}
  aws_access_key_id: ${{ secrets.aws_access_key_id}}
  aws_secret_access_key: ${{ secrets.aws_secret_access_key}}
  CME_API_PASSWORD: ${{secrets.CME_API_PASSWORD}}
  
permissions:
  contents: read

jobs:
  test-flow-load:
    name: Build and apply deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4.4.0
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: "requirements.txt"
    
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --upgrade-strategy eager -r requirements.txt
    
    - name: Save Prefect blocks
      run: |
        prefect blocks register -m prefect_aws
        prefect blocks register -f blocks.py

    - name: Build and apply deployment
      run: |
        prefect deployment build ./aws_flow.py:hello_upload_flow \
        --name "Demo aws flow" \
        -sb s3/s3-bucket \
        -q githubwq \
        -v $GITHUB_SHA \
        --apply
